on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.0
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun --print process.env
        env:
          REPO_NAME: ${{ github.event.repository.name }}
      - run: bun run deploy
        env:
          REPO_NAME: ${{ github.event.repository.name }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
